### ISSUE TITLE
Color Bulb support

### ISSUE THREAD

**Issue by smeird** [bstascavage/plexHue#8] opened 2015-01-17 17:42 UTC
small change to your code, makes hue color bulbs go from playing (dark red) to warm white ( pause / stopped)

def transition(state)
if state == 'playing'
self.class.put("groups/#{self.getPlexGroup}/action", :body => "{\"on\":true, \"hue\":0, \"sat\":254, \"bri\":5, \"transitiontime\":#{$config['hue']['starttransitiontime']}}")
elsif state == 'paused'
self.class.put("groups/#{self.getPlexGroup}/action", :body => "{\"on\":true, \"ct\":500, \"bri\":128, \"transitiontime\":#{$config['hue']['pausedtransitiontime']}}")
elsif state == 'stopped'
self.class.put("groups/#{self.getPlexGroup}/action", :body => "{\"on\":true, \"ct\":500, \"bri\":255, \"transitiontime\":#{$config['hue']['stoptransitiontime']}}")
end
end
end

**Comment by smeird** [comment] 2015-01-17 17:44
small change to your code, makes hue color bulbs go from playing (dark red)  to warm white ( pause / stopped)
---
def transition(state)
        if state == 'playing'
            self.class.put("groups/#{self.getPlexGroup}/action", :body => "{\"on\":true, \"hue\":0, \"sat\":254, \"bri\":5, \"transitiontime\":#{$config['hue']['starttransitiontime']}}")
        elsif state == 'paused'
            self.class.put("groups/#{self.getPlexGroup}/action", :body => "{\"on\":true, \"ct\":500, \"bri\":128, \"transitiontime\":#{$config['hue']['pausedtransitiontime']}}")
        elsif state == 'stopped'
            self.class.put("groups/#{self.getPlexGroup}/action", :body => "{\"on\":true, \"ct\":500, \"bri\":255, \"transitiontime\":#{$config['hue']['stoptransitiontime']}}")
        end
    end
end

**Comment by bstascavage** [comment] 2015-01-17 17:58
1.  This is a preference thing.  While going from dark red to warm white might be pleasing to you, that won't be for everyone.  Further, this code would straight break Hue Lux bulbs, which is what this script was designed for.  If you want to add code to include this feature, please add it as a command-line option, and add config parameters to make this more flexible.
2.  This is Github.  Please submit a Pull Request, instead of adding code via an open issue.

I am going to close this issue, since it isn't a real issue.  This is not to discourage you, as I cannot support color for the moment, and do welcome any contributors that wish to do so.  But it needs to be done in a way to not break existing functionality, and to support all users.

**Closed as completed by bstascavage** 2015-01-17 17:58 UTC
